name: taxi
description: "zkt"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  flutter_azure_b2c: ^0.0.10
  firebase_core: ^3.12.1
  flutter_facebook_auth: ^7.1.1
  http: ^1.3.0
  google_maps_flutter: ^2.10.1
  google_sign_in: ^6.1.1
  microsoft_graph_api: ^0.0.7
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
